"""empty message

Revision ID: 1c4e4a91c760
Revises: None
Create Date: 2017-01-16 15:48:28.169875

"""

# revision identifiers, used by Alembic.
revision = '1c4e4a91c760'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('type', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('course_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('course_section_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_section_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_section_id'], ['course_sections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('section_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_section_id', sa.Integer(), nullable=False),
    sa.Column('week_day', sa.Integer(), nullable=True),
    sa.Column('section_time_start_time', sa.Time(), nullable=True),
    sa.Column('section_time_finish_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['course_section_id'], ['course_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_time_id', sa.Integer(), nullable=True),
    sa.Column('course_section_student_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('section_time_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['course_section_student_id'], ['course_section_students.id'], ),
    sa.ForeignKeyConstraint(['section_time_id'], ['section_times.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_attendance')
    op.drop_table('section_times')
    op.drop_table('course_section_students')
    op.drop_table('course_sections')
    op.drop_table('users')
    op.drop_table('courses')
    # ### end Alembic commands ###
