"""empty message

Revision ID: 30e26d3367b4
Revises: 6faa65472046
Create Date: 2017-02-14 15:40:23.692562

"""

# revision identifiers, used by Alembic.
revision = '30e26d3367b4'
down_revision = '6faa65472046'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('image_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'image_path')
    # ### end Alembic commands ###
