"""empty message

Revision ID: 3c9980b20367
Revises: dbe14822a48b
Create Date: 2016-12-13 22:40:51.832101

"""

# revision identifiers, used by Alembic.
revision = '3c9980b20367'
down_revision = 'dbe14822a48b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('frequency_status', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lesson', 'frequency_status')
    ### end Alembic commands ###
