"""empty message

Revision ID: 654329863631
Revises: 3c9980b20367
Create Date: 2017-01-10 14:49:33.958630

"""

# revision identifiers, used by Alembic.
revision = '654329863631'
down_revision = '3c9980b20367'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('lesson_finish_time', sa.Time(), nullable=True))
    op.add_column('lesson', sa.Column('lesson_start_time', sa.Time(), nullable=True))
    op.add_column('lesson', sa.Column('week_day', sa.Integer(), nullable=True))
    op.drop_column('lesson', 'lesson_finish_date')
    op.drop_column('lesson', 'lesson_start_date')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lesson', sa.Column('lesson_start_date', sa.DATETIME(), nullable=True))
    op.add_column('lesson', sa.Column('lesson_finish_date', sa.DATETIME(), nullable=True))
    op.drop_column('lesson', 'week_day')
    op.drop_column('lesson', 'lesson_start_time')
    op.drop_column('lesson', 'lesson_finish_time')
    # ### end Alembic commands ###
