"""empty message

Revision ID: 6d5aab59eb36
Revises: e5a548254c22
Create Date: 2016-12-08 15:55:05.629179

"""

# revision identifiers, used by Alembic.
revision = '6d5aab59eb36'
down_revision = 'e5a548254c22'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lesson',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('classes_id', sa.Integer(), nullable=False),
    sa.Column('lesson_start_date', sa.DateTime(), nullable=True),
    sa.Column('lesson_finish_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['classes_id'], ['classes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('lesson')
    # ### end Alembic commands ###
