"""empty message

Revision ID: 8a7b2841d633
Revises: None
Create Date: 2017-01-25 15:06:23.014870

"""

# revision identifiers, used by Alembic.
revision = '8a7b2841d633'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user_type_destinations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('param_values_service', sa.String(length=250), nullable=True),
    sa.Column('users_query', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_type_destinations_user_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_type_id', sa.Integer(), nullable=False),
    sa.Column('user_type_destination_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_type_destination_id'], ['user_type_destinations.id'], ),
    sa.ForeignKeyConstraint(['user_type_id'], ['user_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_type_id', 'user_type_destination_id', name='user_type_destinations_user_type_uc')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=250), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('address', sa.String(length=250), nullable=True),
    sa.Column('type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['type'], ['user_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('course_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('teacher_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['teacher_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('wall_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('sender', sa.Integer(), nullable=True),
    sa.Column('destination', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['destination'], ['user_type_destinations.id'], ),
    sa.ForeignKeyConstraint(['sender'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('course_section_students',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_section_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_section_id'], ['course_sections.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_section_id', 'user_id', name='course_section_user_uc')
    )
    op.create_table('section_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_section_id', sa.Integer(), nullable=False),
    sa.Column('week_day', sa.Integer(), nullable=True),
    sa.Column('section_time_start_time', sa.Time(), nullable=True),
    sa.Column('section_time_finish_time', sa.Time(), nullable=True),
    sa.ForeignKeyConstraint(['course_section_id'], ['course_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('student_attendance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section_time_id', sa.Integer(), nullable=True),
    sa.Column('course_section_student_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=1), nullable=True),
    sa.Column('section_time_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['course_section_student_id'], ['course_section_students.id'], ),
    sa.ForeignKeyConstraint(['section_time_id'], ['section_times.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_attendance')
    op.drop_table('section_times')
    op.drop_table('course_section_students')
    op.drop_table('wall_messages')
    op.drop_table('course_sections')
    op.drop_table('users')
    op.drop_table('user_type_destinations_user_type')
    op.drop_table('user_type_destinations')
    op.drop_table('user_type')
    op.drop_table('courses')
    # ### end Alembic commands ###
