"""empty message

Revision ID: aed2eaa53ebb
Revises: 7a916e33a074
Create Date: 2017-01-24 16:53:59.507585

"""

# revision identifiers, used by Alembic.
revision = 'aed2eaa53ebb'
down_revision = '7a916e33a074'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wall_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('sender', sa.Integer(), nullable=True),
    sa.Column('destination', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=140), nullable=True),
    sa.ForeignKeyConstraint(['destination'], ['user_type_destinations.id'], ),
    sa.ForeignKeyConstraint(['sender'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('wall_messages')
    # ### end Alembic commands ###
