"""empty message

Revision ID: fda65376ea5f
Revises: None
Create Date: 2016-11-25 16:02:34.550390

"""

# revision identifiers, used by Alembic.
revision = 'fda65376ea5f'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('turma')
    op.drop_table('disciplina')
    op.drop_table('aluno_turma_table')
    op.drop_column('user', 'tipo')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('tipo', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.create_table('aluno_turma_table',
    sa.Column('turma_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['turma_id'], ['turma.id'], name='aluno_turma_table_turma_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='aluno_turma_table_user_id_fkey'),
    sa.PrimaryKeyConstraint('turma_id', 'user_id', name='aluno_turma_table_pkey')
    )
    op.create_table('disciplina',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('disciplina_id_seq'::regclass)"), nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='disciplina_pkey'),
    sa.UniqueConstraint('codigo', name='disciplina_codigo_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('turma',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('codigo', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('nome', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('disciplina_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('professor_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['disciplina_id'], ['disciplina.id'], name='turma_disciplina_id_fkey'),
    sa.ForeignKeyConstraint(['professor_id'], ['user.id'], name='turma_professor_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='turma_pkey'),
    sa.UniqueConstraint('codigo', name='turma_codigo_key')
    )
    ### end Alembic commands ###
